### PR TITLE
Add parameter for interpolation mode to texture

### PR DESCRIPTION
**Pull request by hobbeshunter**
For my use case it's useful to be able to set the interpolation mode.

### CODE REVIEW

**Comment by robertosfield** [comment]
It may be better to just get the Sampler after construction, or pass in the Sampler rather than pass in a subset of the settings.  If we do the later there is always the chance that someone else we will to set another setting and want to add more to the constructor.

**Comment by hobbeshunter** [comment]
Sounds reasonable. I'll try to pass in a sampler to the constructor as soon as I find time.

**Comment by hobbeshunter** [comment]
@robertosfield is this better?

**Comment by robertosfield** [comment]
Looks good. Now merged.

**Comment by hobbeshunter** [comment]
Thanks

**Pull request merged**
